/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_espace_administrateur (void)
{
  GtkWidget *espace_administrateur;
  GtkWidget *notebook5;
  GtkWidget *notebook8;
  GtkWidget *fixed5598;
  GtkWidget *entry_id_ajout_event;
  GtkWidget *calendar_ajout;
  GtkObject *sb_h_adj;
  GtkWidget *sb_h;
  GtkObject *sb_mn_adj;
  GtkWidget *sb_mn;
  GtkWidget *image6727;
  GtkWidget *entry_nom;
  GtkObject *sb_nbr_adj;
  GtkWidget *sb_nbr;
  GtkWidget *entry_frais;
  GtkWidget *image6834;
  GtkWidget *lab_nom;
  GtkWidget *lab_id;
  GtkWidget *lab_heure;
  GtkWidget *lab_h;
  GtkWidget *lab_date;
  GtkWidget *lab_lieu;
  GtkWidget *lab_frais;
  GtkWidget *lab_type_evt;
  GtkWidget *lab_nbr_inscri;
  GtkWidget *lab_cat;
  GtkWidget *lab_remplissage;
  GtkWidget *lab_mn;
  GtkWidget *butt_retour_admin;
  GtkWidget *alignment6815;
  GtkWidget *hbox102;
  GtkWidget *image6806;
  GtkWidget *label1989199;
  GtkWidget *butt_ajouter;
  GtkWidget *alignment6807;
  GtkWidget *hbox94;
  GtkWidget *image6795;
  GtkWidget *label1989150;
  GtkWidget *rb_homme;
  GSList *rb_homme_group = NULL;
  GtkWidget *rb_femme;
  GtkWidget *rb_mixte;
  GtkWidget *cbox_lieu_ajout;
  GtkWidget *cb_conference;
  GtkWidget *cb_detente_event;
  GtkWidget *cb_competition;
  GtkWidget *entry_calendar_ajout;
  GtkWidget *label144;
  GtkWidget *onglet_modifier;
  GtkWidget *entry_id_event_modif;
  GtkWidget *calendar_modif;
  GtkObject *sp_heure_modif_adj;
  GtkWidget *sp_heure_modif;
  GtkObject *sp_min_event_modif_adj;
  GtkWidget *sp_min_event_modif;
  GtkWidget *image6797;
  GtkWidget *entry_nom_event_modif;
  GtkObject *sb_nbr_modif_adj;
  GtkWidget *sb_nbr_modif;
  GtkWidget *entry_frais_modif;
  GtkWidget *image6833;
  GtkWidget *tv_recherche_if_event;
  GtkWidget *lab_lieu_modif;
  GtkWidget *lab_heure_modif;
  GtkWidget *lab_nom_modif;
  GtkWidget *lab_id_modif;
  GtkWidget *lab_frais_modif;
  GtkWidget *lab_type_evt__modif;
  GtkWidget *lab_date_modif;
  GtkWidget *lab_h_modif;
  GtkWidget *lab_mn_modif;
  GtkWidget *lab_nbr_modif;
  GtkWidget *lab_cat_modif;
  GtkWidget *lab_modifier;
  GtkWidget *cb_detente_modif;
  GtkWidget *cb_competition_modif;
  GtkWidget *cb_conference_modif;
  GtkWidget *butt_actualiser;
  GtkWidget *alignment6898;
  GtkWidget *hbox184;
  GtkWidget *image6952;
  GtkWidget *label1989494;
  GtkWidget *rb_homme_modif;
  GtkWidget *rb_femme_modif;
  GtkWidget *rb_mixte_modif;
  GtkWidget *butt_retour_modif;
  GtkWidget *alignment6810;
  GtkWidget *hbox97;
  GtkWidget *image6800;
  GtkWidget *label1989164;
  GtkWidget *butt_modifier;
  GtkWidget *alignment6809;
  GtkWidget *hbox96;
  GtkWidget *image6799;
  GtkWidget *label1989163;
  GtkWidget *lab_chercher;
  GtkWidget *cbox_lieu_modif;
  GtkWidget *entry_calendar_modif;
  GtkWidget *label1989130;
  GtkWidget *onglet_supprimer;
  GtkWidget *image6705;
  GtkWidget *entry_chercher_nom_event;
  GtkWidget *tv_recherche_evt_supp;
  GtkWidget *entry_id_evt_supp;
  GtkWidget *image6801;
  GtkWidget *lab_chercher_supp;
  GtkWidget *aff_suppress_event;
  GtkWidget *aff_name_event_suppr;
  GtkWidget *aff_type_event;
  GtkWidget *lab_id_evt_supp;
  GtkWidget *cb_conference_supp;
  GtkWidget *butt_retour_supp;
  GtkWidget *alignment6812;
  GtkWidget *hbox99;
  GtkWidget *image6803;
  GtkWidget *label1989172;
  GtkWidget *butt_supp;
  GtkWidget *alignment6813;
  GtkWidget *hbox100;
  GtkWidget *image6804;
  GtkWidget *label1989173;
  GtkWidget *cb_detente_supp;
  GtkWidget *cb_competition_supp;
  GtkWidget *butt_act_supp;
  GtkWidget *alignment6814;
  GtkWidget *hbox101;
  GtkWidget *image6805;
  GtkWidget *label1989174;
  GtkWidget *label153;
  GtkWidget *gestion_evenement;

  espace_administrateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  GTK_WIDGET_SET_FLAGS (espace_administrateur, GTK_CAN_DEFAULT);
  gtk_window_set_title (GTK_WINDOW (espace_administrateur), _("espace administrateur"));

  notebook5 = gtk_notebook_new ();
  gtk_widget_show (notebook5);
  gtk_container_add (GTK_CONTAINER (espace_administrateur), notebook5);
  gtk_widget_set_size_request (notebook5, 1859, -1);

  notebook8 = gtk_notebook_new ();
  gtk_widget_show (notebook8);
  gtk_container_add (GTK_CONTAINER (notebook5), notebook8);
  gtk_widget_set_size_request (notebook8, 1825, 957);

  fixed5598 = gtk_fixed_new ();
  gtk_widget_show (fixed5598);
  gtk_container_add (GTK_CONTAINER (notebook8), fixed5598);

  entry_id_ajout_event = gtk_entry_new ();
  gtk_widget_show (entry_id_ajout_event);
  gtk_fixed_put (GTK_FIXED (fixed5598), entry_id_ajout_event, 352, 152);
  gtk_widget_set_size_request (entry_id_ajout_event, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_ajout_event), 8226);

  calendar_ajout = gtk_calendar_new ();
  gtk_widget_show (calendar_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5598), calendar_ajout, 864, 304);
  gtk_widget_set_size_request (calendar_ajout, 224, 176);
  gtk_calendar_display_options (GTK_CALENDAR (calendar_ajout),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  sb_h_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_h = gtk_spin_button_new (GTK_ADJUSTMENT (sb_h_adj), 1, 0);
  gtk_widget_show (sb_h);
  gtk_fixed_put (GTK_FIXED (fixed5598), sb_h, 352, 304);
  gtk_widget_set_size_request (sb_h, 60, 27);

  sb_mn_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_mn = gtk_spin_button_new (GTK_ADJUSTMENT (sb_mn_adj), 1, 0);
  gtk_widget_show (sb_mn);
  gtk_fixed_put (GTK_FIXED (fixed5598), sb_mn, 480, 304);
  gtk_widget_set_size_request (sb_mn, 60, 27);

  image6727 = create_pixmap (espace_administrateur, "Black and White Typographic Gym Logo.png");
  gtk_widget_show (image6727);
  gtk_fixed_put (GTK_FIXED (fixed5598), image6727, 48, 24);
  gtk_widget_set_size_request (image6727, 215, 90);

  entry_nom = gtk_entry_new ();
  gtk_widget_show (entry_nom);
  gtk_fixed_put (GTK_FIXED (fixed5598), entry_nom, 352, 216);
  gtk_widget_set_size_request (entry_nom, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom), 8226);

  sb_nbr_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_nbr = gtk_spin_button_new (GTK_ADJUSTMENT (sb_nbr_adj), 1, 0);
  gtk_widget_show (sb_nbr);
  gtk_fixed_put (GTK_FIXED (fixed5598), sb_nbr, 392, 608);
  gtk_widget_set_size_request (sb_nbr, 60, 27);

  entry_frais = gtk_entry_new ();
  gtk_widget_show (entry_frais);
  gtk_fixed_put (GTK_FIXED (fixed5598), entry_frais, 352, 456);
  gtk_widget_set_size_request (entry_frais, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_frais), 8226);

  image6834 = create_pixmap (espace_administrateur, "Gymshark's Official Blog.jpg");
  gtk_widget_show (image6834);
  gtk_fixed_put (GTK_FIXED (fixed5598), image6834, 1136, 0);
  gtk_widget_set_size_request (image6834, 700, 1000);

  lab_nom = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Nom:</span>"));
  gtk_widget_show (lab_nom);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_nom, 136, 232);
  gtk_widget_set_size_request (lab_nom, 89, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_nom), TRUE);

  lab_id = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Identifiant:</span>"));
  gtk_widget_show (lab_id);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_id, 136, 152);
  gtk_widget_set_size_request (lab_id, 128, 25);
  gtk_label_set_use_markup (GTK_LABEL (lab_id), TRUE);

  lab_heure = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Horaire:</span>"));
  gtk_widget_show (lab_heure);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_heure, 144, 312);
  gtk_widget_set_size_request (lab_heure, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (lab_heure), TRUE);

  lab_h = gtk_label_new (_("H"));
  gtk_widget_show (lab_h);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_h, 392, 304);
  gtk_widget_set_size_request (lab_h, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_h), TRUE);

  lab_date = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Date:</span>"));
  gtk_widget_show (lab_date);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_date, 792, 304);
  gtk_widget_set_size_request (lab_date, 54, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_date), TRUE);

  lab_lieu = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Lieu:</span>"));
  gtk_widget_show (lab_lieu);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_lieu, 152, 384);
  gtk_widget_set_size_request (lab_lieu, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_lieu), TRUE);

  lab_frais = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Frais d'inscription:</span>"));
  gtk_widget_show (lab_frais);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_frais, 128, 472);
  gtk_widget_set_size_request (lab_frais, 200, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_frais), TRUE);

  lab_type_evt = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Type d'\303\251venement:</span>"));
  gtk_widget_show (lab_type_evt);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_type_evt, 128, 536);
  gtk_widget_set_size_request (lab_type_evt, 192, 33);
  gtk_label_set_use_markup (GTK_LABEL (lab_type_evt), TRUE);

  lab_nbr_inscri = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Nombre des inscrits:</span>"));
  gtk_widget_show (lab_nbr_inscri);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_nbr_inscri, 128, 616);
  gtk_widget_set_size_request (lab_nbr_inscri, 200, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_nbr_inscri), TRUE);

  lab_cat = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Cat\303\251gories participants:</span>"));
  gtk_widget_show (lab_cat);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_cat, 112, 688);
  gtk_widget_set_size_request (lab_cat, 248, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_cat), TRUE);

  lab_remplissage = gtk_label_new (_("<span font= \"Bitstream Charter italic bold 18\"\nforeground=\"Dark red\">Remplissez tous les champs pour cr\303\251er un nouvel \303\251v\303\251nement.</span>"));
  gtk_widget_show (lab_remplissage);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_remplissage, 360, 72);
  gtk_widget_set_size_request (lab_remplissage, 710, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_remplissage), TRUE);

  lab_mn = gtk_label_new (_("Mn"));
  gtk_widget_show (lab_mn);
  gtk_fixed_put (GTK_FIXED (fixed5598), lab_mn, 520, 304);
  gtk_widget_set_size_request (lab_mn, 88, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_mn), TRUE);

  butt_retour_admin = gtk_button_new ();
  gtk_widget_show (butt_retour_admin);
  gtk_fixed_put (GTK_FIXED (fixed5598), butt_retour_admin, 120, 792);
  gtk_widget_set_size_request (butt_retour_admin, 120, 40);

  alignment6815 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6815);
  gtk_container_add (GTK_CONTAINER (butt_retour_admin), alignment6815);

  hbox102 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox102);
  gtk_container_add (GTK_CONTAINER (alignment6815), hbox102);

  image6806 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6806);
  gtk_box_pack_start (GTK_BOX (hbox102), image6806, FALSE, FALSE, 0);

  label1989199 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair display 11\"\nforeground=\"darkred\">Retour</span>"));
  gtk_widget_show (label1989199);
  gtk_box_pack_start (GTK_BOX (hbox102), label1989199, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989199), TRUE);

  butt_ajouter = gtk_button_new ();
  gtk_widget_show (butt_ajouter);
  gtk_fixed_put (GTK_FIXED (fixed5598), butt_ajouter, 864, 776);
  gtk_widget_set_size_request (butt_ajouter, 120, 40);

  alignment6807 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6807);
  gtk_container_add (GTK_CONTAINER (butt_ajouter), alignment6807);

  hbox94 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox94);
  gtk_container_add (GTK_CONTAINER (alignment6807), hbox94);

  image6795 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6795);
  gtk_box_pack_start (GTK_BOX (hbox94), image6795, FALSE, FALSE, 0);

  label1989150 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair display 11\"\nforeground=\"darkgreen\">Ajouter</span>"));
  gtk_widget_show (label1989150);
  gtk_box_pack_start (GTK_BOX (hbox94), label1989150, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989150), TRUE);

  rb_homme = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (rb_homme);
  gtk_fixed_put (GTK_FIXED (fixed5598), rb_homme, 368, 688);
  gtk_widget_set_size_request (rb_homme, 148, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_homme), rb_homme_group);
  rb_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_homme));

  rb_femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (rb_femme);
  gtk_fixed_put (GTK_FIXED (fixed5598), rb_femme, 512, 688);
  gtk_widget_set_size_request (rb_femme, 148, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_femme), rb_homme_group);
  rb_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_femme));

  rb_mixte = gtk_radio_button_new_with_mnemonic (NULL, _("Mixte"));
  gtk_widget_show (rb_mixte);
  gtk_fixed_put (GTK_FIXED (fixed5598), rb_mixte, 656, 688);
  gtk_widget_set_size_request (rb_mixte, 148, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_mixte), rb_homme_group);
  rb_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_mixte));

  cbox_lieu_ajout = gtk_combo_box_new_text ();
  gtk_widget_show (cbox_lieu_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5598), cbox_lieu_ajout, 352, 376);
  gtk_widget_set_size_request (cbox_lieu_ajout, 304, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_ajout), _("Grand_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_ajout), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_ajout), _("Petite_Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_ajout), _("Ben_Arous"));

  cb_conference = gtk_check_button_new_with_mnemonic (_("Conf\303\251rence"));
  gtk_widget_show (cb_conference);
  gtk_fixed_put (GTK_FIXED (fixed5598), cb_conference, 696, 536);
  gtk_widget_set_size_request (cb_conference, 142, 24);

  cb_detente_event = gtk_check_button_new_with_mnemonic (_("D\303\251tente"));
  gtk_widget_show (cb_detente_event);
  gtk_fixed_put (GTK_FIXED (fixed5598), cb_detente_event, 352, 536);
  gtk_widget_set_size_request (cb_detente_event, 142, 24);

  cb_competition = gtk_check_button_new_with_mnemonic (_("Comp\303\251tition"));
  gtk_widget_show (cb_competition);
  gtk_fixed_put (GTK_FIXED (fixed5598), cb_competition, 520, 536);
  gtk_widget_set_size_request (cb_competition, 142, 24);

  entry_calendar_ajout = gtk_entry_new ();
  gtk_widget_show (entry_calendar_ajout);
  gtk_fixed_put (GTK_FIXED (fixed5598), entry_calendar_ajout, 864, 272);
  gtk_widget_set_size_request (entry_calendar_ajout, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_calendar_ajout), 8226);

  label144 = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"#657D55\">Ajouter un \303\251v\303\250nement</span>"));
  gtk_widget_show (label144);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook8), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook8), 0), label144);
  gtk_widget_set_size_request (label144, 240, -1);
  gtk_label_set_use_markup (GTK_LABEL (label144), TRUE);

  onglet_modifier = gtk_fixed_new ();
  gtk_widget_show (onglet_modifier);
  gtk_container_add (GTK_CONTAINER (notebook8), onglet_modifier);

  entry_id_event_modif = gtk_entry_new ();
  gtk_widget_show (entry_id_event_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), entry_id_event_modif, 344, 168);
  gtk_widget_set_size_request (entry_id_event_modif, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_event_modif), 8226);

  calendar_modif = gtk_calendar_new ();
  gtk_widget_show (calendar_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), calendar_modif, 856, 360);
  gtk_widget_set_size_request (calendar_modif, 224, 176);
  gtk_calendar_display_options (GTK_CALENDAR (calendar_modif),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  sp_heure_modif_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sp_heure_modif = gtk_spin_button_new (GTK_ADJUSTMENT (sp_heure_modif_adj), 1, 0);
  gtk_widget_show (sp_heure_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), sp_heure_modif, 344, 408);
  gtk_widget_set_size_request (sp_heure_modif, 60, 27);

  sp_min_event_modif_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sp_min_event_modif = gtk_spin_button_new (GTK_ADJUSTMENT (sp_min_event_modif_adj), 1, 0);
  gtk_widget_show (sp_min_event_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), sp_min_event_modif, 496, 408);
  gtk_widget_set_size_request (sp_min_event_modif, 60, 27);

  image6797 = create_pixmap (espace_administrateur, "Black and White Typographic Gym Logo.png");
  gtk_widget_show (image6797);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), image6797, 48, 24);
  gtk_widget_set_size_request (image6797, 215, 90);

  entry_nom_event_modif = gtk_entry_new ();
  gtk_widget_show (entry_nom_event_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), entry_nom_event_modif, 344, 336);
  gtk_widget_set_size_request (entry_nom_event_modif, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_nom_event_modif), 8226);

  sb_nbr_modif_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  sb_nbr_modif = gtk_spin_button_new (GTK_ADJUSTMENT (sb_nbr_modif_adj), 1, 0);
  gtk_widget_show (sb_nbr_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), sb_nbr_modif, 392, 680);
  gtk_widget_set_size_request (sb_nbr_modif, 60, 27);

  entry_frais_modif = gtk_entry_new ();
  gtk_widget_show (entry_frais_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), entry_frais_modif, 344, 552);
  gtk_widget_set_size_request (entry_frais_modif, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_frais_modif), 8226);

  image6833 = create_pixmap (espace_administrateur, "Gymshark's Official Blog.jpg");
  gtk_widget_show (image6833);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), image6833, 1136, 0);
  gtk_widget_set_size_request (image6833, 700, 1000);

  tv_recherche_if_event = gtk_tree_view_new ();
  gtk_widget_show (tv_recherche_if_event);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), tv_recherche_if_event, 344, 224);
  gtk_widget_set_size_request (tv_recherche_if_event, 352, 88);

  lab_lieu_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Lieu:</span>"));
  gtk_widget_show (lab_lieu_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_lieu_modif, 136, 472);
  gtk_widget_set_size_request (lab_lieu_modif, 49, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_lieu_modif), TRUE);

  lab_heure_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Heure:</span>"));
  gtk_widget_show (lab_heure_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_heure_modif, 128, 408);
  gtk_widget_set_size_request (lab_heure_modif, 80, 16);
  gtk_label_set_use_markup (GTK_LABEL (lab_heure_modif), TRUE);

  lab_nom_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Nom:</span>"));
  gtk_widget_show (lab_nom_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_nom_modif, 120, 360);
  gtk_widget_set_size_request (lab_nom_modif, 89, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_nom_modif), TRUE);

  lab_id_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Identifiant:</span>"));
  gtk_widget_show (lab_id_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_id_modif, 120, 176);
  gtk_widget_set_size_request (lab_id_modif, 128, 25);
  gtk_label_set_use_markup (GTK_LABEL (lab_id_modif), TRUE);

  lab_frais_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Frais d'inscription:</span>"));
  gtk_widget_show (lab_frais_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_frais_modif, 112, 560);
  gtk_widget_set_size_request (lab_frais_modif, 200, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_frais_modif), TRUE);

  lab_type_evt__modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Type d'\303\251venement:</span>"));
  gtk_widget_show (lab_type_evt__modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_type_evt__modif, 120, 616);
  gtk_widget_set_size_request (lab_type_evt__modif, 192, 33);
  gtk_label_set_use_markup (GTK_LABEL (lab_type_evt__modif), TRUE);

  lab_date_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Date:</span>"));
  gtk_widget_show (lab_date_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_date_modif, 784, 360);
  gtk_widget_set_size_request (lab_date_modif, 54, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_date_modif), TRUE);

  lab_h_modif = gtk_label_new (_("H"));
  gtk_widget_show (lab_h_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_h_modif, 392, 408);
  gtk_widget_set_size_request (lab_h_modif, 80, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_h_modif), TRUE);

  lab_mn_modif = gtk_label_new (_("Mn"));
  gtk_widget_show (lab_mn_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_mn_modif, 528, 408);
  gtk_widget_set_size_request (lab_mn_modif, 88, 24);

  lab_nbr_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Nombre des inscrits:</span>"));
  gtk_widget_show (lab_nbr_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_nbr_modif, 128, 688);
  gtk_widget_set_size_request (lab_nbr_modif, 200, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_nbr_modif), TRUE);

  lab_cat_modif = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Cat\303\251gories participants:</span>"));
  gtk_widget_show (lab_cat_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_cat_modif, 104, 752);
  gtk_widget_set_size_request (lab_cat_modif, 248, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_cat_modif), TRUE);

  lab_modifier = gtk_label_new (_("<span font= \"Bitstream Charter italic bold 18\"\nforeground=\"dark red\">Mettez \303\240 jour les informations de l\342\200\231\303\251v\303\251nement s\303\251lectionn\303\251!</span>"));
  gtk_widget_show (lab_modifier);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_modifier, 368, 64);
  gtk_widget_set_size_request (lab_modifier, 702, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_modifier), TRUE);

  cb_detente_modif = gtk_check_button_new_with_mnemonic (_("D\303\251tente"));
  gtk_widget_show (cb_detente_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), cb_detente_modif, 368, 616);
  gtk_widget_set_size_request (cb_detente_modif, 142, 24);

  cb_competition_modif = gtk_check_button_new_with_mnemonic (_("Comp\303\251tition"));
  gtk_widget_show (cb_competition_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), cb_competition_modif, 536, 616);
  gtk_widget_set_size_request (cb_competition_modif, 142, 24);

  cb_conference_modif = gtk_check_button_new_with_mnemonic (_("Conf\303\251rence"));
  gtk_widget_show (cb_conference_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), cb_conference_modif, 712, 616);
  gtk_widget_set_size_request (cb_conference_modif, 142, 24);

  butt_actualiser = gtk_button_new ();
  gtk_widget_show (butt_actualiser);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), butt_actualiser, 720, 224);
  gtk_widget_set_size_request (butt_actualiser, 120, 40);

  alignment6898 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6898);
  gtk_container_add (GTK_CONTAINER (butt_actualiser), alignment6898);

  hbox184 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox184);
  gtk_container_add (GTK_CONTAINER (alignment6898), hbox184);

  image6952 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6952);
  gtk_box_pack_start (GTK_BOX (hbox184), image6952, FALSE, FALSE, 0);

  label1989494 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"darkblue\">Actualiser</span>"));
  gtk_widget_show (label1989494);
  gtk_box_pack_start (GTK_BOX (hbox184), label1989494, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989494), TRUE);

  rb_homme_modif = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (rb_homme_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), rb_homme_modif, 400, 752);
  gtk_widget_set_size_request (rb_homme_modif, 148, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_homme_modif), rb_homme_group);
  rb_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_homme_modif));

  rb_femme_modif = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (rb_femme_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), rb_femme_modif, 552, 752);
  gtk_widget_set_size_request (rb_femme_modif, 148, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_femme_modif), rb_homme_group);
  rb_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_femme_modif));

  rb_mixte_modif = gtk_radio_button_new_with_mnemonic (NULL, _("Mixte"));
  gtk_widget_show (rb_mixte_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), rb_mixte_modif, 696, 752);
  gtk_widget_set_size_request (rb_mixte_modif, 148, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (rb_mixte_modif), rb_homme_group);
  rb_homme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (rb_mixte_modif));

  butt_retour_modif = gtk_button_new ();
  gtk_widget_show (butt_retour_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), butt_retour_modif, 128, 824);
  gtk_widget_set_size_request (butt_retour_modif, 120, 40);

  alignment6810 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6810);
  gtk_container_add (GTK_CONTAINER (butt_retour_modif), alignment6810);

  hbox97 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox97);
  gtk_container_add (GTK_CONTAINER (alignment6810), hbox97);

  image6800 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6800);
  gtk_box_pack_start (GTK_BOX (hbox97), image6800, FALSE, FALSE, 0);

  label1989164 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"darkred\">Retour</span>"));
  gtk_widget_show (label1989164);
  gtk_box_pack_start (GTK_BOX (hbox97), label1989164, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989164), TRUE);

  butt_modifier = gtk_button_new ();
  gtk_widget_show (butt_modifier);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), butt_modifier, 872, 816);
  gtk_widget_set_size_request (butt_modifier, 120, 40);

  alignment6809 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6809);
  gtk_container_add (GTK_CONTAINER (butt_modifier), alignment6809);

  hbox96 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox96);
  gtk_container_add (GTK_CONTAINER (alignment6809), hbox96);

  image6799 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6799);
  gtk_box_pack_start (GTK_BOX (hbox96), image6799, FALSE, FALSE, 0);

  label1989163 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair display 11\"\nforeground=\"darkgreen\">Modifier</span>"));
  gtk_widget_show (label1989163);
  gtk_box_pack_start (GTK_BOX (hbox96), label1989163, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989163), TRUE);

  lab_chercher = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"dark blue\">Chercher un \303\251v\303\250nement:</span>"));
  gtk_widget_show (lab_chercher);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), lab_chercher, 112, 144);
  gtk_widget_set_size_request (lab_chercher, 228, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_chercher), TRUE);

  cbox_lieu_modif = gtk_combo_box_new_text ();
  gtk_widget_show (cbox_lieu_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), cbox_lieu_modif, 352, 472);
  gtk_widget_set_size_request (cbox_lieu_modif, 288, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_modif), _("Grand_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_modif), _("Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_modif), _("Petite_Ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbox_lieu_modif), _("Ben_Arous"));

  entry_calendar_modif = gtk_entry_new ();
  gtk_widget_show (entry_calendar_modif);
  gtk_fixed_put (GTK_FIXED (onglet_modifier), entry_calendar_modif, 856, 328);
  gtk_widget_set_size_request (entry_calendar_modif, 224, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_calendar_modif), 8226);

  label1989130 = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"#657D55\">Modifier un \303\251v\303\250nement</span>"));
  gtk_widget_show (label1989130);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook8), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook8), 1), label1989130);
  gtk_widget_set_size_request (label1989130, 240, -1);
  gtk_label_set_use_markup (GTK_LABEL (label1989130), TRUE);

  onglet_supprimer = gtk_fixed_new ();
  gtk_widget_show (onglet_supprimer);
  gtk_container_add (GTK_CONTAINER (notebook8), onglet_supprimer);

  image6705 = create_pixmap (espace_administrateur, "Black and White Typographic Gym Logo.png");
  gtk_widget_show (image6705);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), image6705, 48, 24);
  gtk_widget_set_size_request (image6705, 215, 90);

  entry_chercher_nom_event = gtk_entry_new ();
  gtk_widget_show (entry_chercher_nom_event);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), entry_chercher_nom_event, 552, 216);
  gtk_widget_set_size_request (entry_chercher_nom_event, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_chercher_nom_event), 8226);

  tv_recherche_evt_supp = gtk_tree_view_new ();
  gtk_widget_show (tv_recherche_evt_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), tv_recherche_evt_supp, 568, 424);
  gtk_widget_set_size_request (tv_recherche_evt_supp, 336, 240);

  entry_id_evt_supp = gtk_entry_new ();
  gtk_widget_show (entry_id_evt_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), entry_id_evt_supp, 560, 720);
  gtk_widget_set_size_request (entry_id_evt_supp, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_evt_supp), 8226);

  image6801 = create_pixmap (espace_administrateur, "Gymshark's Official Blog.jpg");
  gtk_widget_show (image6801);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), image6801, 1136, 0);
  gtk_widget_set_size_request (image6801, 700, 1000);

  lab_chercher_supp = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"darkblue\">Chercher un \303\251v\303\250nement:</span>"));
  gtk_widget_show (lab_chercher_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), lab_chercher_supp, 128, 176);
  gtk_widget_set_size_request (lab_chercher_supp, 248, 32);
  gtk_label_set_use_markup (GTK_LABEL (lab_chercher_supp), TRUE);

  aff_suppress_event = gtk_label_new (_("<span font= \"Bitstream Charter italic bold 18\"\nforeground=\"dark red\">Supprimez l\342\200\231\303\251v\303\251nement choisi. \nCette op\303\251ration ne peut pas \303\252tre annul\303\251e.</span>"));
  gtk_widget_show (aff_suppress_event);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), aff_suppress_event, 400, 48);
  gtk_widget_set_size_request (aff_suppress_event, 580, 71);
  gtk_label_set_use_markup (GTK_LABEL (aff_suppress_event), TRUE);
  gtk_label_set_justify (GTK_LABEL (aff_suppress_event), GTK_JUSTIFY_CENTER);

  aff_name_event_suppr = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Nom:</span>"));
  gtk_widget_show (aff_name_event_suppr);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), aff_name_event_suppr, 360, 224);
  gtk_widget_set_size_request (aff_name_event_suppr, 89, 17);
  gtk_label_set_use_markup (GTK_LABEL (aff_name_event_suppr), TRUE);

  aff_type_event = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Type d'\303\251venement:</span>"));
  gtk_widget_show (aff_type_event);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), aff_type_event, 368, 280);
  gtk_widget_set_size_request (aff_type_event, 192, 33);
  gtk_label_set_use_markup (GTK_LABEL (aff_type_event), TRUE);

  lab_id_evt_supp = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">identifiant de l'\303\251v\303\250nement:</span>"));
  gtk_widget_show (lab_id_evt_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), lab_id_evt_supp, 296, 728);
  gtk_widget_set_size_request (lab_id_evt_supp, 224, 24);
  gtk_label_set_use_markup (GTK_LABEL (lab_id_evt_supp), TRUE);

  cb_conference_supp = gtk_check_button_new_with_mnemonic (_("Conf\303\251rence"));
  gtk_widget_show (cb_conference_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), cb_conference_supp, 832, 288);
  gtk_widget_set_size_request (cb_conference_supp, 142, 24);

  butt_retour_supp = gtk_button_new ();
  gtk_widget_show (butt_retour_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), butt_retour_supp, 200, 808);
  gtk_widget_set_size_request (butt_retour_supp, 120, 40);

  alignment6812 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6812);
  gtk_container_add (GTK_CONTAINER (butt_retour_supp), alignment6812);

  hbox99 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox99);
  gtk_container_add (GTK_CONTAINER (alignment6812), hbox99);

  image6803 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6803);
  gtk_box_pack_start (GTK_BOX (hbox99), image6803, FALSE, FALSE, 0);

  label1989172 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"darkred\">Retour</span>"));
  gtk_widget_show (label1989172);
  gtk_box_pack_start (GTK_BOX (hbox99), label1989172, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989172), TRUE);

  butt_supp = gtk_button_new ();
  gtk_widget_show (butt_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), butt_supp, 912, 816);
  gtk_widget_set_size_request (butt_supp, 120, 40);

  alignment6813 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6813);
  gtk_container_add (GTK_CONTAINER (butt_supp), alignment6813);

  hbox100 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox100);
  gtk_container_add (GTK_CONTAINER (alignment6813), hbox100);

  image6804 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6804);
  gtk_box_pack_start (GTK_BOX (hbox100), image6804, FALSE, FALSE, 0);

  label1989173 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"red\">Supprimer</span>"));
  gtk_widget_show (label1989173);
  gtk_box_pack_start (GTK_BOX (hbox100), label1989173, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989173), TRUE);

  cb_detente_supp = gtk_check_button_new_with_mnemonic (_("D\303\251tente"));
  gtk_widget_show (cb_detente_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), cb_detente_supp, 568, 288);
  gtk_widget_set_size_request (cb_detente_supp, 142, 24);

  cb_competition_supp = gtk_check_button_new_with_mnemonic (_("Comp\303\251tition"));
  gtk_widget_show (cb_competition_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), cb_competition_supp, 688, 288);
  gtk_widget_set_size_request (cb_competition_supp, 142, 24);

  butt_act_supp = gtk_button_new ();
  gtk_widget_show (butt_act_supp);
  gtk_fixed_put (GTK_FIXED (onglet_supprimer), butt_act_supp, 784, 376);
  gtk_widget_set_size_request (butt_act_supp, 120, 40);

  alignment6814 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6814);
  gtk_container_add (GTK_CONTAINER (butt_act_supp), alignment6814);

  hbox101 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox101);
  gtk_container_add (GTK_CONTAINER (alignment6814), hbox101);

  image6805 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6805);
  gtk_box_pack_start (GTK_BOX (hbox101), image6805, FALSE, FALSE, 0);

  label1989174 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"darkblue\">Actualiser</span>"));
  gtk_widget_show (label1989174);
  gtk_box_pack_start (GTK_BOX (hbox101), label1989174, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989174), TRUE);

  label153 = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"#657D55\">Supprimer un \303\251v\303\250nement</span>"));
  gtk_widget_show (label153);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook8), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook8), 2), label153);
  gtk_widget_set_size_request (label153, 240, -1);
  gtk_label_set_use_markup (GTK_LABEL (label153), TRUE);

  gestion_evenement = gtk_label_new_with_mnemonic (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"#A000\">G\303\251rer les \303\251v\303\250nements</span>"));
  gtk_widget_show (gestion_evenement);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 0), gestion_evenement);
  gtk_widget_set_size_request (gestion_evenement, 197, -1);
  gtk_label_set_use_markup (GTK_LABEL (gestion_evenement), TRUE);
  gtk_misc_set_alignment (GTK_MISC (gestion_evenement), 0.6, 0.5);

  g_signal_connect ((gpointer) calendar_ajout, "day_selected",
                    G_CALLBACK (on_calendar_ajout_day_selected),
                    NULL);
  g_signal_connect ((gpointer) butt_retour_admin, "clicked",
                    G_CALLBACK (on_butt_retour_admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) butt_ajouter, "clicked",
                    G_CALLBACK (on_butt_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) rb_homme, "toggled",
                    G_CALLBACK (on_rb_homme_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb_femme, "toggled",
                    G_CALLBACK (on_rb_femme_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb_mixte, "toggled",
                    G_CALLBACK (on_rb_mixte_toggled),
                    NULL);
  g_signal_connect ((gpointer) cb_conference, "toggled",
                    G_CALLBACK (on_cb_conference_toggled),
                    NULL);
  g_signal_connect ((gpointer) cb_detente_event, "toggled",
                    G_CALLBACK (on_cb_detente_event_toggled),
                    NULL);
  g_signal_connect ((gpointer) cb_competition, "toggled",
                    G_CALLBACK (on_cb_competition_toggled),
                    NULL);
  g_signal_connect ((gpointer) entry_calendar_ajout, "focus_in_event",
                    G_CALLBACK (on_entry_calendar_ajout_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) calendar_modif, "day_selected",
                    G_CALLBACK (on_calendar_modif_day_selected),
                    NULL);
  g_signal_connect ((gpointer) tv_recherche_if_event, "row_activated",
                    G_CALLBACK (on_tv_recherche_if_event_row_activated),
                    NULL);
  g_signal_connect ((gpointer) cb_detente_modif, "toggled",
                    G_CALLBACK (on_cb_detente_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) cb_competition_modif, "toggled",
                    G_CALLBACK (on_cb_competition_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) cb_conference_modif, "toggled",
                    G_CALLBACK (on_cb_conference_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) butt_actualiser, "clicked",
                    G_CALLBACK (on_butt_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) rb_homme_modif, "toggled",
                    G_CALLBACK (on_rb_homme_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb_femme_modif, "toggled",
                    G_CALLBACK (on_rb_femme_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) rb_mixte_modif, "toggled",
                    G_CALLBACK (on_rb_mixte_modif_toggled),
                    NULL);
  g_signal_connect ((gpointer) butt_retour_modif, "clicked",
                    G_CALLBACK (on_butt_retour_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) butt_modifier, "clicked",
                    G_CALLBACK (on_butt_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) entry_calendar_modif, "focus_in_event",
                    G_CALLBACK (on_entry_calendar_modif_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) tv_recherche_evt_supp, "row_activated",
                    G_CALLBACK (on_tv_recherche_evt_supp_row_activated),
                    NULL);
  g_signal_connect ((gpointer) cb_conference_supp, "toggled",
                    G_CALLBACK (on_cb_conference_supp_toggled),
                    NULL);
  g_signal_connect ((gpointer) butt_retour_supp, "clicked",
                    G_CALLBACK (on_butt_retour_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) butt_supp, "clicked",
                    G_CALLBACK (on_butt_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) cb_detente_supp, "toggled",
                    G_CALLBACK (on_cb_detente_supp_toggled),
                    NULL);
  g_signal_connect ((gpointer) cb_competition_supp, "toggled",
                    G_CALLBACK (on_cb_competition_supp_toggled),
                    NULL);
  g_signal_connect ((gpointer) butt_act_supp, "clicked",
                    G_CALLBACK (on_butt_act_supp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_administrateur, espace_administrateur, "espace_administrateur");
  GLADE_HOOKUP_OBJECT (espace_administrateur, notebook5, "notebook5");
  GLADE_HOOKUP_OBJECT (espace_administrateur, notebook8, "notebook8");
  GLADE_HOOKUP_OBJECT (espace_administrateur, fixed5598, "fixed5598");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_id_ajout_event, "entry_id_ajout_event");
  GLADE_HOOKUP_OBJECT (espace_administrateur, calendar_ajout, "calendar_ajout");
  GLADE_HOOKUP_OBJECT (espace_administrateur, sb_h, "sb_h");
  GLADE_HOOKUP_OBJECT (espace_administrateur, sb_mn, "sb_mn");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6727, "image6727");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_nom, "entry_nom");
  GLADE_HOOKUP_OBJECT (espace_administrateur, sb_nbr, "sb_nbr");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_frais, "entry_frais");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6834, "image6834");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_nom, "lab_nom");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_id, "lab_id");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_heure, "lab_heure");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_h, "lab_h");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_date, "lab_date");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_lieu, "lab_lieu");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_frais, "lab_frais");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_type_evt, "lab_type_evt");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_nbr_inscri, "lab_nbr_inscri");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_cat, "lab_cat");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_remplissage, "lab_remplissage");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_mn, "lab_mn");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_retour_admin, "butt_retour_admin");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6815, "alignment6815");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox102, "hbox102");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6806, "image6806");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989199, "label1989199");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_ajouter, "butt_ajouter");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6807, "alignment6807");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox94, "hbox94");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6795, "image6795");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989150, "label1989150");
  GLADE_HOOKUP_OBJECT (espace_administrateur, rb_homme, "rb_homme");
  GLADE_HOOKUP_OBJECT (espace_administrateur, rb_femme, "rb_femme");
  GLADE_HOOKUP_OBJECT (espace_administrateur, rb_mixte, "rb_mixte");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cbox_lieu_ajout, "cbox_lieu_ajout");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_conference, "cb_conference");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_detente_event, "cb_detente_event");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_competition, "cb_competition");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_calendar_ajout, "entry_calendar_ajout");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label144, "label144");
  GLADE_HOOKUP_OBJECT (espace_administrateur, onglet_modifier, "onglet_modifier");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_id_event_modif, "entry_id_event_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, calendar_modif, "calendar_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, sp_heure_modif, "sp_heure_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, sp_min_event_modif, "sp_min_event_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6797, "image6797");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_nom_event_modif, "entry_nom_event_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, sb_nbr_modif, "sb_nbr_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_frais_modif, "entry_frais_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6833, "image6833");
  GLADE_HOOKUP_OBJECT (espace_administrateur, tv_recherche_if_event, "tv_recherche_if_event");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_lieu_modif, "lab_lieu_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_heure_modif, "lab_heure_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_nom_modif, "lab_nom_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_id_modif, "lab_id_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_frais_modif, "lab_frais_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_type_evt__modif, "lab_type_evt__modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_date_modif, "lab_date_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_h_modif, "lab_h_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_mn_modif, "lab_mn_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_nbr_modif, "lab_nbr_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_cat_modif, "lab_cat_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_modifier, "lab_modifier");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_detente_modif, "cb_detente_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_competition_modif, "cb_competition_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_conference_modif, "cb_conference_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_actualiser, "butt_actualiser");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6898, "alignment6898");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox184, "hbox184");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6952, "image6952");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989494, "label1989494");
  GLADE_HOOKUP_OBJECT (espace_administrateur, rb_homme_modif, "rb_homme_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, rb_femme_modif, "rb_femme_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, rb_mixte_modif, "rb_mixte_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_retour_modif, "butt_retour_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6810, "alignment6810");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox97, "hbox97");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6800, "image6800");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989164, "label1989164");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_modifier, "butt_modifier");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6809, "alignment6809");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox96, "hbox96");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6799, "image6799");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989163, "label1989163");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_chercher, "lab_chercher");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cbox_lieu_modif, "cbox_lieu_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_calendar_modif, "entry_calendar_modif");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989130, "label1989130");
  GLADE_HOOKUP_OBJECT (espace_administrateur, onglet_supprimer, "onglet_supprimer");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6705, "image6705");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_chercher_nom_event, "entry_chercher_nom_event");
  GLADE_HOOKUP_OBJECT (espace_administrateur, tv_recherche_evt_supp, "tv_recherche_evt_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, entry_id_evt_supp, "entry_id_evt_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6801, "image6801");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_chercher_supp, "lab_chercher_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, aff_suppress_event, "aff_suppress_event");
  GLADE_HOOKUP_OBJECT (espace_administrateur, aff_name_event_suppr, "aff_name_event_suppr");
  GLADE_HOOKUP_OBJECT (espace_administrateur, aff_type_event, "aff_type_event");
  GLADE_HOOKUP_OBJECT (espace_administrateur, lab_id_evt_supp, "lab_id_evt_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_conference_supp, "cb_conference_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_retour_supp, "butt_retour_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6812, "alignment6812");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox99, "hbox99");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6803, "image6803");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989172, "label1989172");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_supp, "butt_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6813, "alignment6813");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox100, "hbox100");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6804, "image6804");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989173, "label1989173");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_detente_supp, "cb_detente_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, cb_competition_supp, "cb_competition_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, butt_act_supp, "butt_act_supp");
  GLADE_HOOKUP_OBJECT (espace_administrateur, alignment6814, "alignment6814");
  GLADE_HOOKUP_OBJECT (espace_administrateur, hbox101, "hbox101");
  GLADE_HOOKUP_OBJECT (espace_administrateur, image6805, "image6805");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label1989174, "label1989174");
  GLADE_HOOKUP_OBJECT (espace_administrateur, label153, "label153");
  GLADE_HOOKUP_OBJECT (espace_administrateur, gestion_evenement, "gestion_evenement");

  return espace_administrateur;
}

GtkWidget*
create_espace_membre (void)
{
  GtkWidget *espace_membre;
  GtkWidget *notebook9;
  GtkWidget *notebook11;
  GtkWidget *fixed33;
  GtkWidget *image6712;
  GtkWidget *treeview_participer;
  GtkWidget *entry_id_participer;
  GtkWidget *image6774;
  GtkWidget *image6773;
  GtkWidget *lab_type_participer;
  GtkWidget *lab_participer;
  GtkWidget *butt_retour_participer;
  GtkWidget *alignment6826;
  GtkWidget *hbox113;
  GtkWidget *image6819;
  GtkWidget *butt_ret;
  GtkWidget *butt_inscri_participer;
  GtkWidget *butt_inscri;
  GtkWidget *hbox112;
  GtkWidget *image6818;
  GtkWidget *label1989233;
  GtkWidget *cb_detente_participer;
  GtkWidget *cb_conference_participer;
  GtkWidget *cb_competition_participer;
  GtkWidget *lab_id_participer;
  GtkWidget *lab_id_participant;
  GtkWidget *entry_participant;
  GtkWidget *butt_act_participer;
  GtkWidget *alignment6824;
  GtkWidget *hbox111;
  GtkWidget *image6817;
  GtkWidget *butt_act;
  GtkWidget *label196;
  GtkWidget *fixed5610;
  GtkWidget *treeview_inscri;
  GtkWidget *label1989303;
  GtkWidget *image6855;
  GtkWidget *image6862;
  GtkWidget *image6863;
  GtkWidget *label_inscri_evt;
  GtkWidget *butt_retour_inscri;
  GtkWidget *alignment6839;
  GtkWidget *hbox126;
  GtkWidget *image6860;
  GtkWidget *label1989305;
  GtkWidget *butt_act_inscri;
  GtkWidget *alignment6840;
  GtkWidget *hbox127;
  GtkWidget *image6861;
  GtkWidget *label1989306;
  GtkWidget *label1989302;
  GtkWidget *partucip_event_memb;

  espace_membre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (espace_membre), _("espace Membre"));

  notebook9 = gtk_notebook_new ();
  gtk_widget_show (notebook9);
  gtk_container_add (GTK_CONTAINER (espace_membre), notebook9);

  notebook11 = gtk_notebook_new ();
  gtk_widget_show (notebook11);
  gtk_container_add (GTK_CONTAINER (notebook9), notebook11);
  gtk_widget_set_size_request (notebook11, 1853, 957);

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (notebook11), fixed33);

  image6712 = create_pixmap (espace_membre, "Black and White Typographic Gym Logo.png");
  gtk_widget_show (image6712);
  gtk_fixed_put (GTK_FIXED (fixed33), image6712, 48, 24);
  gtk_widget_set_size_request (image6712, 215, 90);

  treeview_participer = gtk_tree_view_new ();
  gtk_widget_show (treeview_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), treeview_participer, 496, 304);
  gtk_widget_set_size_request (treeview_participer, 300, 200);

  entry_id_participer = gtk_entry_new ();
  gtk_widget_show (entry_id_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), entry_id_participer, 472, 624);
  gtk_widget_set_size_request (entry_id_participer, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_participer), 8226);

  image6774 = create_pixmap (espace_membre, "e9cbcd3b-6cf5-493e-954e-616d700ac337.jpg");
  gtk_widget_show (image6774);
  gtk_fixed_put (GTK_FIXED (fixed33), image6774, 1152, 0);
  gtk_widget_set_size_request (image6774, 733, 416);

  image6773 = create_pixmap (espace_membre, "Beach Bootcamp Wrong Gym during Sunset.jpg");
  gtk_widget_show (image6773);
  gtk_fixed_put (GTK_FIXED (fixed33), image6773, 1152, 416);
  gtk_widget_set_size_request (image6773, 732, 484);

  lab_type_participer = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Type d'\303\251venement:</span>"));
  gtk_widget_show (lab_type_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), lab_type_participer, 160, 216);
  gtk_widget_set_size_request (lab_type_participer, 192, 33);
  gtk_label_set_use_markup (GTK_LABEL (lab_type_participer), TRUE);

  lab_participer = gtk_label_new (_("<span font= \"Bitstream Charter italic bold 18\"\nforeground=\"#A000\">Vivez l\342\200\231exp\303\251rience, participez \303\240 notre prochain \303\251v\303\251nement !</span>"));
  gtk_widget_show (lab_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), lab_participer, 376, 56);
  gtk_widget_set_size_request (lab_participer, 690, 48);
  gtk_label_set_use_markup (GTK_LABEL (lab_participer), TRUE);

  butt_retour_participer = gtk_button_new ();
  gtk_widget_show (butt_retour_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), butt_retour_participer, 336, 752);
  gtk_widget_set_size_request (butt_retour_participer, 120, 40);

  alignment6826 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6826);
  gtk_container_add (GTK_CONTAINER (butt_retour_participer), alignment6826);

  hbox113 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox113);
  gtk_container_add (GTK_CONTAINER (alignment6826), hbox113);

  image6819 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6819);
  gtk_box_pack_start (GTK_BOX (hbox113), image6819, FALSE, FALSE, 0);

  butt_ret = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"Black\">Retour</span>"));
  gtk_widget_show (butt_ret);
  gtk_box_pack_start (GTK_BOX (hbox113), butt_ret, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (butt_ret), TRUE);

  butt_inscri_participer = gtk_button_new ();
  gtk_widget_show (butt_inscri_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), butt_inscri_participer, 824, 752);
  gtk_widget_set_size_request (butt_inscri_participer, 120, 40);

  butt_inscri = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (butt_inscri);
  gtk_container_add (GTK_CONTAINER (butt_inscri_participer), butt_inscri);

  hbox112 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox112);
  gtk_container_add (GTK_CONTAINER (butt_inscri), hbox112);

  image6818 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6818);
  gtk_box_pack_start (GTK_BOX (hbox112), image6818, FALSE, FALSE, 0);

  label1989233 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"Black\">S'inscrire</span>"));
  gtk_widget_show (label1989233);
  gtk_box_pack_start (GTK_BOX (hbox112), label1989233, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989233), TRUE);

  cb_detente_participer = gtk_check_button_new_with_mnemonic (_("D\303\251tente"));
  gtk_widget_show (cb_detente_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), cb_detente_participer, 552, 216);
  gtk_widget_set_size_request (cb_detente_participer, 142, 24);

  cb_conference_participer = gtk_check_button_new_with_mnemonic (_("Conf\303\251rence"));
  gtk_widget_show (cb_conference_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), cb_conference_participer, 712, 216);
  gtk_widget_set_size_request (cb_conference_participer, 142, 24);

  cb_competition_participer = gtk_check_button_new_with_mnemonic (_("Comp\303\251tition"));
  gtk_widget_show (cb_competition_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), cb_competition_participer, 376, 216);
  gtk_widget_set_size_request (cb_competition_participer, 142, 24);

  lab_id_participer = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Identifiant de l'\303\251v\303\250nement:</span>"));
  gtk_widget_show (lab_id_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), lab_id_participer, 184, 632);
  gtk_widget_set_size_request (lab_id_participer, 231, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_id_participer), TRUE);

  lab_id_participant = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"black\">Identifiant de participant:</span>"));
  gtk_widget_show (lab_id_participant);
  gtk_fixed_put (GTK_FIXED (fixed33), lab_id_participant, 184, 696);
  gtk_widget_set_size_request (lab_id_participant, 231, 17);
  gtk_label_set_use_markup (GTK_LABEL (lab_id_participant), TRUE);

  entry_participant = gtk_entry_new ();
  gtk_widget_show (entry_participant);
  gtk_fixed_put (GTK_FIXED (fixed33), entry_participant, 472, 680);
  gtk_widget_set_size_request (entry_participant, 350, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_participant), 8226);

  butt_act_participer = gtk_button_new ();
  gtk_widget_show (butt_act_participer);
  gtk_fixed_put (GTK_FIXED (fixed33), butt_act_participer, 680, 512);
  gtk_widget_set_size_request (butt_act_participer, 120, 40);

  alignment6824 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6824);
  gtk_container_add (GTK_CONTAINER (butt_act_participer), alignment6824);

  hbox111 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox111);
  gtk_container_add (GTK_CONTAINER (alignment6824), hbox111);

  image6817 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6817);
  gtk_box_pack_start (GTK_BOX (hbox111), image6817, FALSE, FALSE, 0);

  butt_act = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (butt_act);
  gtk_box_pack_start (GTK_BOX (hbox111), butt_act, FALSE, FALSE, 0);

  label196 = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"#657D55\">Participer </span>"));
  gtk_widget_show (label196);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook11), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook11), 0), label196);
  gtk_widget_set_size_request (label196, 240, -1);
  gtk_label_set_use_markup (GTK_LABEL (label196), TRUE);

  fixed5610 = gtk_fixed_new ();
  gtk_widget_show (fixed5610);
  gtk_container_add (GTK_CONTAINER (notebook11), fixed5610);

  treeview_inscri = gtk_tree_view_new ();
  gtk_widget_show (treeview_inscri);
  gtk_fixed_put (GTK_FIXED (fixed5610), treeview_inscri, 528, 192);
  gtk_widget_set_size_request (treeview_inscri, 464, 280);

  label1989303 = gtk_label_new ("");
  gtk_widget_show (label1989303);
  gtk_fixed_put (GTK_FIXED (fixed5610), label1989303, 440, 72);
  gtk_widget_set_size_request (label1989303, 48, 16);

  image6855 = create_pixmap (espace_membre, "Black and White Typographic Gym Logo.png");
  gtk_widget_show (image6855);
  gtk_fixed_put (GTK_FIXED (fixed5610), image6855, 48, 24);
  gtk_widget_set_size_request (image6855, 215, 90);

  image6862 = create_pixmap (espace_membre, "e9cbcd3b-6cf5-493e-954e-616d700ac337.jpg");
  gtk_widget_show (image6862);
  gtk_fixed_put (GTK_FIXED (fixed5610), image6862, 1152, 0);
  gtk_widget_set_size_request (image6862, 733, 416);

  image6863 = create_pixmap (espace_membre, "Beach Bootcamp Wrong Gym during Sunset.jpg");
  gtk_widget_show (image6863);
  gtk_fixed_put (GTK_FIXED (fixed5610), image6863, 1152, 416);
  gtk_widget_set_size_request (image6863, 732, 484);

  label_inscri_evt = gtk_label_new (_("<span font= \"Bitstream Charter 15\"\nforeground=\"dark red\">\303\211v\303\250nements auxquels vous \303\251tes inscrit(e):</span>"));
  gtk_widget_show (label_inscri_evt);
  gtk_fixed_put (GTK_FIXED (fixed5610), label_inscri_evt, 400, 112);
  gtk_widget_set_size_request (label_inscri_evt, 408, 48);
  gtk_label_set_use_markup (GTK_LABEL (label_inscri_evt), TRUE);

  butt_retour_inscri = gtk_button_new ();
  gtk_widget_show (butt_retour_inscri);
  gtk_fixed_put (GTK_FIXED (fixed5610), butt_retour_inscri, 472, 584);
  gtk_widget_set_size_request (butt_retour_inscri, 120, 40);

  alignment6839 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6839);
  gtk_container_add (GTK_CONTAINER (butt_retour_inscri), alignment6839);

  hbox126 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox126);
  gtk_container_add (GTK_CONTAINER (alignment6839), hbox126);

  image6860 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6860);
  gtk_box_pack_start (GTK_BOX (hbox126), image6860, FALSE, FALSE, 0);

  label1989305 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"Black\">Retour</span>"));
  gtk_widget_show (label1989305);
  gtk_box_pack_start (GTK_BOX (hbox126), label1989305, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989305), TRUE);

  butt_act_inscri = gtk_button_new ();
  gtk_widget_show (butt_act_inscri);
  gtk_fixed_put (GTK_FIXED (fixed5610), butt_act_inscri, 1008, 584);
  gtk_widget_set_size_request (butt_act_inscri, 120, 40);

  alignment6840 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6840);
  gtk_container_add (GTK_CONTAINER (butt_act_inscri), alignment6840);

  hbox127 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox127);
  gtk_container_add (GTK_CONTAINER (alignment6840), hbox127);

  image6861 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6861);
  gtk_box_pack_start (GTK_BOX (hbox127), image6861, FALSE, FALSE, 0);

  label1989306 = gtk_label_new_with_mnemonic (_("<span font= \"Playfair Display 11\"\nforeground=\"Black\">Actualiser</span>"));
  gtk_widget_show (label1989306);
  gtk_box_pack_start (GTK_BOX (hbox127), label1989306, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label1989306), TRUE);

  label1989302 = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"#657D55\">Mes inscriptions </span>"));
  gtk_widget_show (label1989302);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook11), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook11), 1), label1989302);
  gtk_widget_set_size_request (label1989302, 240, -1);
  gtk_label_set_use_markup (GTK_LABEL (label1989302), TRUE);

  partucip_event_memb = gtk_label_new (_("<span font= \"Bitstream Charter bold 13\"\nforeground=\"#A000\">Participer  \303\240 un \303\251v\303\250nement</span>"));
  gtk_widget_show (partucip_event_memb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook9), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook9), 0), partucip_event_memb);
  gtk_widget_set_size_request (partucip_event_memb, 234, -1);
  gtk_label_set_use_markup (GTK_LABEL (partucip_event_memb), TRUE);

  g_signal_connect ((gpointer) treeview_participer, "row_activated",
                    G_CALLBACK (on_treeview_participer_row_activated),
                    NULL);
  g_signal_connect ((gpointer) butt_retour_participer, "clicked",
                    G_CALLBACK (on_butt_retour_participer_clicked),
                    NULL);
  g_signal_connect ((gpointer) butt_inscri_participer, "clicked",
                    G_CALLBACK (on_butt_inscri_participer_clicked),
                    NULL);
  g_signal_connect ((gpointer) butt_act_participer, "clicked",
                    G_CALLBACK (on_butt_act_participer_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_inscri, "row_activated",
                    G_CALLBACK (on_treeview_inscri_row_activated),
                    NULL);
  g_signal_connect ((gpointer) butt_retour_inscri, "clicked",
                    G_CALLBACK (on_butt_retour_inscri_clicked),
                    NULL);
  g_signal_connect ((gpointer) butt_act_inscri, "clicked",
                    G_CALLBACK (on_butt_act_inscri_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (espace_membre, espace_membre, "espace_membre");
  GLADE_HOOKUP_OBJECT (espace_membre, notebook9, "notebook9");
  GLADE_HOOKUP_OBJECT (espace_membre, notebook11, "notebook11");
  GLADE_HOOKUP_OBJECT (espace_membre, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (espace_membre, image6712, "image6712");
  GLADE_HOOKUP_OBJECT (espace_membre, treeview_participer, "treeview_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, entry_id_participer, "entry_id_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, image6774, "image6774");
  GLADE_HOOKUP_OBJECT (espace_membre, image6773, "image6773");
  GLADE_HOOKUP_OBJECT (espace_membre, lab_type_participer, "lab_type_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, lab_participer, "lab_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_retour_participer, "butt_retour_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, alignment6826, "alignment6826");
  GLADE_HOOKUP_OBJECT (espace_membre, hbox113, "hbox113");
  GLADE_HOOKUP_OBJECT (espace_membre, image6819, "image6819");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_ret, "butt_ret");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_inscri_participer, "butt_inscri_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_inscri, "butt_inscri");
  GLADE_HOOKUP_OBJECT (espace_membre, hbox112, "hbox112");
  GLADE_HOOKUP_OBJECT (espace_membre, image6818, "image6818");
  GLADE_HOOKUP_OBJECT (espace_membre, label1989233, "label1989233");
  GLADE_HOOKUP_OBJECT (espace_membre, cb_detente_participer, "cb_detente_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, cb_conference_participer, "cb_conference_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, cb_competition_participer, "cb_competition_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, lab_id_participer, "lab_id_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, lab_id_participant, "lab_id_participant");
  GLADE_HOOKUP_OBJECT (espace_membre, entry_participant, "entry_participant");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_act_participer, "butt_act_participer");
  GLADE_HOOKUP_OBJECT (espace_membre, alignment6824, "alignment6824");
  GLADE_HOOKUP_OBJECT (espace_membre, hbox111, "hbox111");
  GLADE_HOOKUP_OBJECT (espace_membre, image6817, "image6817");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_act, "butt_act");
  GLADE_HOOKUP_OBJECT (espace_membre, label196, "label196");
  GLADE_HOOKUP_OBJECT (espace_membre, fixed5610, "fixed5610");
  GLADE_HOOKUP_OBJECT (espace_membre, treeview_inscri, "treeview_inscri");
  GLADE_HOOKUP_OBJECT (espace_membre, label1989303, "label1989303");
  GLADE_HOOKUP_OBJECT (espace_membre, image6855, "image6855");
  GLADE_HOOKUP_OBJECT (espace_membre, image6862, "image6862");
  GLADE_HOOKUP_OBJECT (espace_membre, image6863, "image6863");
  GLADE_HOOKUP_OBJECT (espace_membre, label_inscri_evt, "label_inscri_evt");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_retour_inscri, "butt_retour_inscri");
  GLADE_HOOKUP_OBJECT (espace_membre, alignment6839, "alignment6839");
  GLADE_HOOKUP_OBJECT (espace_membre, hbox126, "hbox126");
  GLADE_HOOKUP_OBJECT (espace_membre, image6860, "image6860");
  GLADE_HOOKUP_OBJECT (espace_membre, label1989305, "label1989305");
  GLADE_HOOKUP_OBJECT (espace_membre, butt_act_inscri, "butt_act_inscri");
  GLADE_HOOKUP_OBJECT (espace_membre, alignment6840, "alignment6840");
  GLADE_HOOKUP_OBJECT (espace_membre, hbox127, "hbox127");
  GLADE_HOOKUP_OBJECT (espace_membre, image6861, "image6861");
  GLADE_HOOKUP_OBJECT (espace_membre, label1989306, "label1989306");
  GLADE_HOOKUP_OBJECT (espace_membre, label1989302, "label1989302");
  GLADE_HOOKUP_OBJECT (espace_membre, partucip_event_memb, "partucip_event_memb");

  return espace_membre;
}

GtkWidget*
create_Statistique (void)
{
  GtkWidget *Statistique;
  GtkWidget *fixed5611;
  GtkWidget *drawingarea1;
  GtkWidget *butt_stat;

  Statistique = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Statistique), _("window1"));

  fixed5611 = gtk_fixed_new ();
  gtk_widget_show (fixed5611);
  gtk_container_add (GTK_CONTAINER (Statistique), fixed5611);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_show (drawingarea1);
  gtk_fixed_put (GTK_FIXED (fixed5611), drawingarea1, 384, 64);
  gtk_widget_set_size_request (drawingarea1, 456, 328);

  butt_stat = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (butt_stat);
  gtk_fixed_put (GTK_FIXED (fixed5611), butt_stat, 568, 464);
  gtk_widget_set_size_request (butt_stat, 104, 40);

  g_signal_connect ((gpointer) drawingarea1, "expose_event",
                    G_CALLBACK (on_drawingarea1_expose_event),
                    NULL);
  g_signal_connect ((gpointer) butt_stat, "clicked",
                    G_CALLBACK (on_butt_stat_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Statistique, Statistique, "Statistique");
  GLADE_HOOKUP_OBJECT (Statistique, fixed5611, "fixed5611");
  GLADE_HOOKUP_OBJECT (Statistique, drawingarea1, "drawingarea1");
  GLADE_HOOKUP_OBJECT (Statistique, butt_stat, "butt_stat");

  return Statistique;
}

