/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_administrateur (void);
GtkWidget* create_espace_membre (void);
GtkWidget* create_espace_entraineur (void);
GtkWidget* create_Acceuil_admin (void);
GtkWidget* create_Acceuil_entraineur (void);
GtkWidget* create_Acceuil_membre (void);
GtkWidget* create_Dashboard (void);
GtkWidget* create_Inscription (void);
GtkWidget* create_inputdialog1 (void);
