/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#include "gestion_cours.h"
#include <gtk/gtk.h>
#include <stdio.h>
#include <locale.h>
#include "interface.h"
#include "support.h"
#include "callbacks.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Dashboard;
  GtkWidget *Inscription;
  GtkWidget *espace_administrateur;
  GtkWidget *espace_membre;
  GtkWidget *espace_entraineur;
  GtkWidget *Acceuil_admin;
  GtkWidget *Acceuil_entraineur;
  GtkWidget *Acceuil_membre;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif
  setlocale(LC_ALL, "");
  //gtk_set_locale ();
  gtk_init (&argc, &argv);
nettoyer_cours("cours.txt", "inscrient.txt");
if (argc > 1) {
    if (strstr(argv[1], "mymotion://inscription")) {
    GtkWidget *window = create_espace_membre(); // ta fonction qui crée la fenêtre principale
GtkNotebook *notebook10 = GTK_NOTEBOOK(lookup_widget(window, "notebook10"));
        afficher_page_inscription(notebook10,0);
    }
}
  add_pixmap_directory ("../pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
 Dashboard = create_Dashboard ();
  gtk_widget_show (Dashboard);
  Inscription = create_Inscription ();
  gtk_widget_show (Inscription);

  espace_administrateur = create_espace_administrateur ();
  gtk_widget_show (espace_administrateur);
  espace_membre = create_espace_membre ();
  gtk_widget_show (espace_membre);
GtkWidget *btn_contact;

btn_contact = lookup_widget(espace_membre, "contact_mem");
g_signal_connect(btn_contact, "clicked",
                 G_CALLBACK(on_contact_mem_clicked),
                 NULL);
  espace_entraineur = create_espace_entraineur ();
  gtk_widget_show (espace_entraineur);
  Acceuil_admin = create_Acceuil_admin ();
  gtk_widget_show (Acceuil_admin);
  Acceuil_entraineur = create_Acceuil_entraineur ();
  gtk_widget_show (Acceuil_entraineur);
  Acceuil_membre = create_Acceuil_membre ();
  gtk_widget_show (Acceuil_membre);

  gtk_main ();
  return 0;
}

